// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Instructions() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex flex-col gap-12 items-center justify-evenly text-center p-2\"><h3 class=\"text-3xl font-semibold max-w-[600px]\">How to download Twitch Media for Free using Twitch<span class=\"text-purple-400\">Rip</span>?</h3><div class=\"flex w-full items-start justify-center gap-12\"><div class=\"flex flex-col items-center justify-start\"><div class=\"inline-flex items-center justify-center rounded-md outline-2 outline outline-violet-500 p-3 w-max mb-3\"><i class=\"fa-solid fa-copy m-0 text-violet-500 text-3xl\"></i></div><h4 class=\"text-2xl font-semibold\">Get the Media URL</h4><p>Open the media which you want to download, copy the media or video link.</p></div><div class=\"flex flex-col items-center justify-start\"><div class=\"inline-flex items-center justify-center rounded-md outline-2 outline outline-violet-500 p-3 w-max mb-3\"><i class=\"fa-solid fa-paste m-0 text-violet-500 text-3xl\"></i></div><h4 class=\"text-2xl font-semibold\">Paste the Media URL</h4><p>Paste the video URL which you copied from the earlier step and paste it on the download bar.</p></div><div class=\"flex flex-col items-center justify-start\"><div class=\"inline-flex items-center justify-center rounded-md outline-2 outline outline-violet-500 p-3 w-max mb-3\"><i class=\"fa-solid fa-download m-0 text-violet-500 text-3xl\"></i></div><h4 class=\"text-2xl font-semibold\">Download the Media</h4><p>Select the resolution and start downloading your Twitch media for free.</p></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
